#!/bin/bash
# Quick Start Guide for Ethereum Calldata Analysis Tool

set -e

echo "=== Ethereum Calldata Analysis Tool - Quick Start ==="
echo ""
echo "This tool analyzes smart contract calldata sizes on Ethereum over a specified time period."
echo ""
echo "STEP 1: Get an Etherscan API Key"
echo "  1. Visit: https://etherscan.io/apis"
echo "  2. Create an account or log in"
echo "  3. Generate a free API key"
echo "  4. Copy your API key"
echo ""
echo "STEP 2: Create Your Config File"
echo "  Choose one of these formats:"
echo "    - config.json    (most common)"
echo "    - config.yml     (YAML format)"
echo "    - config.toml    (TOML format)"
echo "    - config.csv     (CSV format)"
echo "    - config.txt     (simple text format)"
echo ""
echo "  Example (JSON):"
echo "  {"
echo "    \"etherscan_api_key\": \"YOUR_API_KEY_HERE\","
echo "    \"network\": \"mainnet\","
echo "    \"days_back\": 7,"
echo "    \"contracts\": ["
echo "      {"
echo "        \"address\": \"0x1111111254fb6c44bac0bed2854e76f90643097d\","
echo "        \"name\": \"1inch Router\","
echo "        \"functions\": ["
echo "          {\"name\": \"swap\", \"selector\": \"0x7c025200\"},"
echo "          {\"name\": \"fillOrder\", \"selector\": \"0xd0a3b665\"}"
echo "        ]"
echo "      }"
echo "    ]"
echo "  }"
echo ""
echo "STEP 3: Find Function Selectors"
echo "  Option A: Use 4byte.directory"
echo "    Visit: https://www.4byte.directory/"
echo "    Search for your function: e.g., 'swap(address[],uint256)'"
echo ""
echo "  Option B: Calculate manually"
echo "    Take first 4 bytes of keccak256(function_signature)"
echo "    Example: keccak256('swap(...)') → 0x7c025200"
echo ""
echo "STEP 4: Run the Analysis"
echo "  ./eth-analysis -config config.json -output text"
echo ""
echo "Available output formats:"
echo "  - json  (default, parseable)"
echo "  - csv   (spreadsheet-friendly)"
echo "  - text  (human-readable table)"
echo ""
echo "STEP 5: Interpret Results"
echo "  Each function will show:"
echo "    - Count:      How many calls in the period"
echo "    - Min/Max:    Smallest and largest calldata size"
echo "    - Mean:       Average calldata size"
echo "    - Median:     Middle value (50th percentile)"
echo "    - Mode:       Most common calldata size"
echo ""
echo "EXAMPLE RUN (1 week of 1inch Router):"
echo "  ./eth-analysis -config config.json -output text"
echo ""
echo "=== 1inch Router ==="
echo "Function                       Count      Min          Max        Mean       Median       Mode       Mode Cnt"
echo "----------------------------------------------------"
echo "swap                           1250       196          4096       852.50     768.00       512        183"
echo ""
echo "This means:"
echo "  - 1250 'swap' calls in the past week"
echo "  - Smallest calldata: 196 bytes"
echo "  - Largest calldata: 4096 bytes"
echo "  - Average: 852.50 bytes"
echo "  - Most common: 512 bytes (appeared 183 times)"
echo ""
